version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
  postgresdb-data:
    driver: local
